server:
  tomcat:
    accesslog:
      prefix: tomcat
      pattern: '%a %t "%r" %s %b (%D ms)'
      enabled: 'true'
      directory: tomcat
    basedir: ${logging.file.path}
  compression:
    enabled: 'true'
    mime-types: text/html, text/xml, text/plain, text/css, text/javascript, application/javascript,
      application/json
    min-response-size: '4096'
  port: '9010'
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: none
  profiles:
    active: '@spring.profiles.active@'
unravel:
  config:
    report-response: Thanks for reporting this. Your feedback has been received successfully
      and appropriate action shall be taken within 24 hours.
